# 网站名称
site_name: SimXHub.org - PDPS 仿真操作技巧
site_description: 'Tecnomatix Process Simulate (PDPS) 仿真操作技巧与资源中心'
site_author: '名字或昵称'
site_url: 'https://www.simxhub.org/' # 等部署后，这里填最终域名


# 主题
theme:
  name: material

# 在这里配置导航栏
nav:
  - '首页': 'index.md'
  - 'PDPS入门':
    - '软件安装与激活': 'getting-started/installation.md'
    - '初识操作界面': 'getting-started/ui-overview.md'
  - '核心技巧':
    - '机器人路径规划': 'core-skills/robot-path.md'
    - '碰撞检测与分析': 'core-skills/collision-detection.md'
  - '关于我们': 'about.md'

# 关键！应用 Material 主题
theme:
  name: material
  language: zh  # 设置语言为中文
  logo: assets/logo.svg  # 网站Logo (稍后我们会创建它)
  favicon: assets/favicon.png # 网站图标 

  # 配色方案
  palette:
    # 日间模式
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    # 暗色模式
    - scheme: slate
      primary: blue
      accent: light-blue
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式
        

  # 功能开关
  features:
    - navigation.instant  # 页面加载无需刷新，体验极好
    - navigation.tabs     # 启用顶部导航标签
    - navigation.top      # 返回顶部按钮
    - search.suggest      # 搜索时显示建议
    - search.highlight    # 高亮搜索关键词
    - content.code.annotate # 代码块注释功能
    - content.tabs.link   # 可链接的内容选项卡

# Markdown 扩展 (让文章更强大)
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition # 美化的提示框，如 note, warning
  - attr_list
  - md_in_html

# 版权信息
copyright: 'Copyright © 2025 SimXHub.org'